// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUaDgsonn9-atW7_arD40c8aCuTTUEbaQ',
    appId: '1:343927315522:web:b2dfc70d9eafc15c0221db',
    messagingSenderId: '343927315522',
    projectId: 'lambda-c242a',
    authDomain: 'lambda-c242a.firebaseapp.com',
    storageBucket: 'lambda-c242a.firebasestorage.app',
    measurementId: 'G-2TBD1Q9FTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABK9sStfV1LThdx1xeojKLuj444jGAOPY',
    appId: '1:343927315522:android:3fc2b06f783335800221db',
    messagingSenderId: '343927315522',
    projectId: 'lambda-c242a',
    storageBucket: 'lambda-c242a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkrM7ony7l75cpyohXz1aDBRD0MmhRsHc',
    appId: '1:343927315522:ios:b76f4abb1c3a180c0221db',
    messagingSenderId: '343927315522',
    projectId: 'lambda-c242a',
    storageBucket: 'lambda-c242a.firebasestorage.app',
    iosBundleId: 'com.example.lambdaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkrM7ony7l75cpyohXz1aDBRD0MmhRsHc',
    appId: '1:343927315522:ios:b76f4abb1c3a180c0221db',
    messagingSenderId: '343927315522',
    projectId: 'lambda-c242a',
    storageBucket: 'lambda-c242a.firebasestorage.app',
    iosBundleId: 'com.example.lambdaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUaDgsonn9-atW7_arD40c8aCuTTUEbaQ',
    appId: '1:343927315522:web:eb8d9c34937a78630221db',
    messagingSenderId: '343927315522',
    projectId: 'lambda-c242a',
    authDomain: 'lambda-c242a.firebaseapp.com',
    storageBucket: 'lambda-c242a.firebasestorage.app',
    measurementId: 'G-EWH05EGBV8',
  );
}
